
name: Android Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r23b
        add-to-path: false

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      # run: ./gradlew build
      run: ./gradlew assembleRelease

    - id: tag
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d_%H-%M")"

    - run: |
        cd ${{ github.workspace }}/app/build/outputs/apk/release/
        mv app-release.apk app-release-${{ github.ref }}-${{ steps.tag.outputs.release_tag }}.apk
      name: Move and Rename APK

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}-${{ steps.tag.outputs.release_tag }}
        files: ${{ github.workspace }}/app/build/outputs/apk/release/app-release-${{ github.ref }}-${{ steps.tag.outputs.release_tag }}.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
