name: Android Release v2

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11
        # cache: gradle

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r24
        add-to-path: false

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: true
      
    - name: Build with Gradle
      run: |
        ./gradlew build
      # ./gradlew assembleDebug --stacktrace --info --warning-mode all

    - id: tag
      run: |
        tag=$(date +"v%Y-%m-%d-%H-%M")
        echo "Generated release tag: $tag"
        echo "::set-output name=release_tag::$tag"
      # Format date as vYYYY-MM-DD-HH-MM

    - id: print_apk_path
      run: |  
        find ${{ github.workspace }} -name "*.apk"
      shell: bash

    - id: find_apk_path
      run: |  
        echo "::set-output name=apk_path::$(find \${{ github.workspace }} -name "*.apk")"

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: ${{ steps.find_apk_path.outputs.apk_path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
