name: Manual Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      # with:
      #   ref: dev
      # submodules: true

    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: 11
        # temurin, zulu, adopt, adopt-hotspot, adopt-openj9, liberica, microsoft, corretto, semeru, oracle, dragonwell
        # cache: gradle

      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@v4
      #   with:
      #     cache-read-only: false

#    - name: Setup CMake
#      uses: lukka/get-cmake@latest
#      with:
#        cmakeVersion: 3.10.2

    - name: Install Android SDK
      run: |
        sudo apt-get update > /dev/null 
        sudo apt-get install -y wget unzip > /dev/null 

        wget -O "commandlinetools-linux-9123335_latest.zip" \
          https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip > /dev/null 2>&1 
        mkdir -p $HOME/sdk/
        unzip -qod $HOME/sdk/ commandlinetools-linux-9123335_latest.zip

        echo "===> ls $HOME/sdk/ :" && ls $HOME/sdk/

        mv $HOME/sdk/cmdline-tools $HOME/sdk/latest
        mkdir -p $HOME/sdk/cmdline-tools
        mv $HOME/sdk/latest $HOME/sdk/cmdline-tools/

        echo "===> ls $HOME/sdk/cmdline-tools/latest/bin/ :" && ls $HOME/sdk/cmdline-tools/latest/bin/

        export GRADLE_USER_HOME=$HOME/gradle_home
        export ANDROID_HOME=$HOME/sdk
        export ANDROID_SDK_ROOT=$HOME/sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        echo "HOME="$HOME
        
        java -version
        cmake --version
        gcc --version
        
        echo "sdk.dir=$HOME/sdk" >> local.properties
        echo "ndk.dir=$HOME/sdk/ndk/24.0.8215888" >> local.properties

        yes | sdkmanager --licenses || true
        echo "===> sdkmanager install <===" && \
        yes | sdkmanager --install "platforms;android-30" "build-tools;30.0.3" "platform-tools" || true && \
        yes | sdkmanager --install "ndk;24.0.8215888" || true

        chmod +x gradlew
      shell: bash

    - name: Build with Gradle
      run: |
        ./gradlew assembleRelease
      # build assembleDebug --stacktrace --info --debug --warning-mode all

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          /home/runner/gradle_home
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/gradle-wrapper.jar') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - id: tag
      run: |
        tag=$(date +"v%Y-%m-%d-%H-%M")
        echo "Generated release tag: $tag"
        echo "release_tag=${tag}" >> "$GITHUB_OUTPUT"
      # Format date as vYYYY-MM-DD-HH-MM

    - id: print_apk_path
      run: |
        whoami
        sudo df -h
        sudo du -sh ${{ github.workspace }}
        apk_path=$(find ${{ github.workspace }}/app/ -name "Scene_*_release.apk")
        echo "apk_path=$apk_path" >> "$GITHUB_OUTPUT"
        env
        echo $apk_path
      shell: bash

    - uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          ${{ steps.print_apk_path.outputs.apk_path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
