name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'microsoft'

      - name: Install Android SDK
        run: |
          sudo apt-get update > /dev/null 
          sudo apt-get install -y wget unzip > /dev/null 
          
          wget -O "commandlinetools-linux-9123335_latest.zip" \
            https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip > /dev/null 2>&1 
          mkdir -p $HOME/sdk/
          unzip -qod $HOME/sdk/ commandlinetools-linux-9123335_latest.zip
          
          echo "===> ls $HOME/sdk/ :" && \
          ls $HOME/sdk/
          
          mv $HOME/sdk/cmdline-tools $HOME/sdk/latest
          mkdir -p $HOME/sdk/cmdline-tools
          mv $HOME/sdk/latest $HOME/sdk/cmdline-tools/
          
          echo "===> ls $HOME/sdk/cmdline-tools/latest/bin/ :" && \
          ls $HOME/sdk/cmdline-tools/latest/bin/
          
          export GRADLE_USER_HOME=$HOME/gradle_home
          export ANDROID_HOME=$HOME/sdk
          export ANDROID_SDK_ROOT=$HOME/sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          
          echo "sdk.dir=$HOME/sdk" >> local.properties
          echo "ndk.dir=$HOME/sdk/ndk/24.0.8215888" >> local.properties
          
          echo "yes\nyes\nyes\nyes\nyes\nyes" | sdkmanager --licenses
          echo "===> sdkmanager install <===" && \
          echo "yes" | sdkmanager --install "platforms;android-30" "build-tools;30.0.3" "platform-tools" "ndk;24.0.8215888"
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          java -version
          cmake --version
          gcc --version
          ./gradlew assembleRelease

      - name: Get tag from GITHUB_REF
        id: tag
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          echo "Release tag: $tag"
          echo "::set-output name=release_tag::$tag"

      - id: print_apk_path
        run: |
          whoami
          sudo df -h
          sudo du -sh ${{ github.workspace }}
          env
          sudo find ${{ github.workspace }} -name "Scene_*_release.apk"
        shell: bash

      - id: apk_path
        run: |
          echo "{apk_path}={$(find \${{ github.workspace }}/app/build/outputs/apk/release/ -name "Scene_*_release.apk")}" >> $GITHUB_STATE

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ${{ steps.apk_path.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
